version: '3.8'
services:
  elastic:
    image: elasticsearch:8.7.1
    volumes:
      - ./elastic_data:/usr/share/elasticsearch/data
    networks:
      - backsite
    environment:
      ELASTIC_PASSWORD: backsite
  db:
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_USER: backsite
      POSTGRES_PASSWORD: backsite
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - backsite
  web:
    build: 
      context: ./application
    ports:
      - 8080:80
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: backsite
      POSTGRES_PASSWORD: backsite
      POSTGRES_DB_NAME: backsite
    networks:
      - backsite
    depends_on:
      - db
      - elastic
    volumes:
      - ./configuration:/opt/configuration


networks:
  backsite:
    driver: bridge